### ISSUE TITLE
fix recipe lint: SPDX, etc

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/deap-feedstock#13]
didn't quite get it through on #12, but we should investigate the correct license string to appease the linter.

**Comment by ocefpaf** [comment]
This lint is a more of a suggestion, nice to get it fixed though so automated tools can parse the licenses.

**Comment by bollwyvl** [comment]
Things Not Strings!

**Comment by bollwyvl** [comment]
Fixed by #17
