### ISSUE TITLE
Updating version

### ISSUE THREAD

**Issue by TiemenSch** [conda-forge/deap-feedstock#4]
Would it be possible to bump the DEAP version to a later one? They currently are at 1.2.2 and this recipe fixes it to 1.0.2 if I'm not mistaken.

**Comment by bollwyvl** [comment]
It looks like the linux builds [aren't working](https://circleci.com/gh/conda-forge/deap-feedstock/15), in a similar vein to conda-forge/statsd-feedstock#3 and conda-forge/cfchecker-feedstock#7...

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

@ericdill @ocefpaf @jschueller has our understanding of the underlying issue changed?

**Comment by bollwyvl** [comment]
Rekicking the missing builds on circle finished the builds!
